on:
  workflow_call:
    secrets:
      SEMGREP_APP_TOKEN:
        required: true

jobs:
  Semgrep:
    if: ${{ ( contains('pull_request', github.event_name) && github.event.action != 'closed' ) }}
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Semgrep
        uses: njjetha/semgrep-action@master
        with:
          token: ${{ secrets.SEMGREP_APP_TOKEN }}
  
  copyright-license-detector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history so we can diff properly
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
 
      - name: Add PR base repo as remote and fetch it
        run: |
          git remote add upstream https://github.com/${{ github.event.pull_request.base.repo.full_name }}.git
          git fetch upstream
 
      - name: Generate final patch between base and head
        run: |
          git diff upstream/${{ github.event.pull_request.base.ref }} > pr.patch
          head -n 100 pr.patch

      - name: Run copyright/license detector
        uses: qualcomm/copyright-license-checker-action@main
        with:
          patch_file: pr.patch
          repo_name: ${{ github.repository }}